### ISSUE TITLE
when going back via `u` - cursor should remember its position

### ISSUE THREAD

**Issue by gingerlime** [ryanss/vim-hackernews#11]
Thaks for creating this plugin. It's really nice.

One small improvement would be to be able to go back (via `u`) and continue from where you were at. Also perhaps you could use a new buffer so then the vim built-in buffer navigation can work well, and you can just pull out / in.

**Comment by sagarjauhari** [comment]
+1

**Comment by sagarjauhari** [comment]
This also fixes #6

**Comment by trOmy** [comment]
+11

**Comment by sagarjauhari** [comment]
Thanks for the fix. It would be nice to see multiple buffers being used and allow VIM to take care of this automatically in the future.
