### ISSUE TITLE
HackerNews.vim Error: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by jkup** [ryanss/vim-hackernews#14]
I installed via pathogen on vim 7.4.

When I try to :HackerNews I just get this error:

.hackernews" [New File]
HackerNews.vim Error: HTTP Error 503: Service Unavailable
Press ENTER or type command to continue

Then if I hit enter I see the orange header show up but no news items. Any ideas?

**Comment by jkup** [comment]
Just seeing similar issues in https://github.com/ryanss/vim-hackernews/issues/13

Is this the same problem? Sorry if it's a double-post.

**Comment by ryanss** [comment]
The API that this plugin uses has been down for a majority of the day unfortunately.

https://github.com/cheeaun/node-hnapi/

**Comment by ryanss** [comment]
The API is back up again now.

**Comment by jkup** [comment]
Awesome! Works great now, thanks!

**Comment by jaredculp** [comment]
This is down again

**Comment by ryanss** [comment]
It is up again and I received a message from the author of the API this plugin is using and he just put through some fixes which will hopefully stop his API from going down again.

**Comment by jkup** [comment]
:+1:
