### ISSUE TITLE
Plugin errors out when no background colour is specified.

### ISSUE THREAD

**Issue by ffledgling** [ryanss/vim-hackernews#15]
I have the following line in my vimrc:
```
highlight Normal ctermbg=NONE
```
So as to disable the background colour by the colourscheme with my transparent terminal, but this causes the Plugin to error out with the following:
```
Error detected while processing :
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path to home>/vim/bundle/vim-hackernews/plugin/hackernews.py", line 49, in hacker_news
    vim.command("edit .hackernews")
vim.error: Vim(highlight):E420: BG color unknown
```

Disabling the aforementioned line from the vimrc fixes the issue. Can something be done about this?

**Comment by ryanss** [comment]
This error is fixed but unfortunately it looks like there's no way to completely hide the Hacker News item ID (ex. `[9018129]`) at the end of each front page line when `ctermbg=NONE`.

You might need to manually set `ctermfg` to a colour close to your desktop background when `filetype=hackernews`.

**Comment by ffledgling** [comment]
Not sure what you mean by fixed here, I just pulled in the latest update and although I no longer get an error with `ctermbg=NONE`, it seems to *force* a background colour (based on my colorscheme/theme) for Vim, not sure if that was the intended behaviour of the fix, but it seems a little too overbearing if it is intentional.
Would it not be possible to do one of the following:
1. Remove the news item entry from the end of the line entirely?
2. Simply leave it in place in the case where `ctermbg` is set to `NONE`?
3. Only force the background behaviour when `filetype` is set to `hackernews`?

**Comment by ryanss** [comment]
All the fix does is wrap the setting of the `Ignore` highlight group *foreground* color to the current background color in a `try/catch` block to stop `E420: BG color unknown` error from occurring when `ctermbg=None`. It's not doing anything to set a background color.

As for  point 3, all this syntax highlighting is set only for `filetype=hackernews`. You can test this by pasting the contents of the `.hackernews` buffer into another buffer and see it looks completely different.

If you can mess around with the `syntax/hackernews.vim` file and improve how it behaves with your particular vim configuration please submit a pull request or patch with the changes.

**Comment by ffledgling** [comment]
*As for point 3, all this syntax highlighting is set only for `filetype=hackernews`. You can test this by pasting the contents of the `.hackernews` buffer into another buffer and see it looks completely different.*

This makes since as the intended behaviour, but unfortunately, this is not the behaviour I observed. Starting vim with any file when the vim-hackernews plugin is loaded seems to force a background colour. Disabling the plugin fixes the issue, so I'm inclined to think it's something in either (i) the plugin itself or (ii) the way the plugin and my vimrc interact with each other.

Regardless, I'll try to fiddle around with both my `.vimrc` and `vim-hackernews`. If I find the root cause, I'll try to get a patch in. if I can't I'll at the very least report findings on this thread.

**Comment by ryanss** [comment]
There have been a lot of changes and updates to the plugin the last few days. One of them made the plugin not load until the first time `:HackerNews` is run. Update your copy of the plugin and see if any of the updates have improved your situation.

**Comment by ffledgling** [comment]
This update definitely helps!
For now when I view HackerNews with `ctermbg=None`, there is no background enforced, and although I see the numbers next to the news titles, it's something I'll happily live with.
Thanks!
