### ISSUE TITLE
Breaks arrow keys functionality in insert mode

### ISSUE THREAD

**Issue by jonalmeida** [ryanss/vim-hackernews#17]
When using vim-hackernews via Pathogen, trying to move the cursor in insert mode with the arrow keys doesn't work.

**Comment by ryanss** [comment]
The vim-hackernews plugin does very little key remapping and doesn't touch the arrow keys, but to help find the culprit of this problem do the following:
* Open a blank vim buffer and run the command `:map <right>`. What is the output?
* Now run `:HackerNews` to open the front page story list and type the same command. What is the output?

**Comment by jonalmeida** [comment]
Hey Ryan, sorry for the bother. I think it must have been something else then There isn't any mapping for the right arrow keys in both cases, but I could have sworn that after removing vim-hackernews the right arrow mapping problems went away.

If I come across it again, I'll open another issue with better info.

Cheers!
