### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by John-Lin** [ryanss/vim-hackernews#19]
I got 503 Service Unavailable

".hackernews" [New File]
HackerNews.vim Error: HTTP Error 503: Service Unavailable
Press ENTER or type command to continue

The API URL failed http://node-hnapi.herokuapp.com/news

**Comment by ryanss** [comment]
There has been some issues with the API but the author is actively addressing them and seems to have things under control now.

https://github.com/cheeaun/node-hnapi
