### ISSUE TITLE
Missing HTMLParser

### ISSUE THREAD

**Issue by rhowell** [ryanss/vim-hackernews#20]
I'm attempting to use vim-hackernews on Yosemite 10.10.2 and am receiving the following error:

    Error detected while processing /Users/rhowell/.vim/bundle/vim-hackernews/plugin/hackernews.vim:
    line   25:
    Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/Users/rhowell/.vim/bundle/vim-hackernews/plugin/hackernews.py", line 13, in <module>
          import HTMLParser
    ImportError: No module named HTMLParser

I'm running vim 7.4 huge version with MacVim GUI installed via Homebrew.  If you need more specifics about the python version etc... I'd be happy to provide it.

Thanks for taking the time to investigate.

**Comment by ryanss** [comment]
Can you run the following vim commands and provide the output:
* `:version`
* `:python import sys; print sys.version`

**Comment by rhowell** [comment]
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2014 09:49:07)
MacOS X (unix) version
Included patches: 1-258
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +clientserver    +cscope          +emacs_tags      +folding         +jumplist        -lua             -mouse_jsbterm   -mzscheme        +profile         +signs           +tag_old_static  +transparency    +wildignore      -xterm_clipboard
+arabic          +clipboard       +cursorbind      +eval            -footer          +keymap          +menu            +mouse_netterm   +netbeans_intg   +python          +smartindent     -tag_any_white   +user_commands   +wildmenu        -xterm_save
+autocmd         +cmdline_compl   +cursorshape     +ex_extra        +fork()          +langmap         +mksession       +mouse_sgr       +odbeditor       -python3         -sniff           +tcl             +vertsplit       +windows         -xpm
+balloon_eval    +cmdline_hist    +dialog_con_gui  +extra_search    +fullscreen      +libcall         +modify_fname    -mouse_sysmouse  +path_extra      +quickfix        +startuptime     +terminfo        +virtualedit     +writebackup
+browse          +cmdline_info    +diff            +farsi           -gettext         +linebreak       +mouse           +mouse_urxvt     +perl            +reltime         +statusline      +termresponse    +visual          -X11
++builtin_terms  +comments        +digraphs        +file_in_path    -hangul_input    +lispindent      +mouseshape      +mouse_xterm     +persistent_undo +rightleft       -sun_workshop    +textobjects     +visualextra     -xfontset
+byte_offset     +conceal         +dnd             +find_in_path    +iconv           +listcmds        +mouse_dec       +multi_byte      +postscript      +ruby            +syntax          +title           +viminfo         +xim
+cindent         +cryptv          -ebcdic          +float           +insert_expand   +localmap        -mouse_gpm       +multi_lang      +printer         +scrollbind      +tag_binary      +toolbar         +vreplace        -xsmp
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-s
trict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_S
OURCE=1     -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -framework CoreFoundation -lpython2.7 -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Co
coa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

:python import sys; print sys.version

    2.7.6 (default, Sep  9 2014, 15:04:36)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

**Comment by ryanss** [comment]
Two more things to try:
* Run the vim command `:python import sys; print sys.path` and paste the output
* Run this command in the terminal and paste the output:
```
ls /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py*
```

Thanks.

**Comment by rhowell** [comment]
```:python import sys; print sys.path``` returns the following:

    '/Users/rhowell/Library/Python/2.7/lib/python/site-packages', '/Library/Python/2.7/site-packages', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg', '/usr/local/lib/python2.7/site-packages', '_vim_path_']

```ls /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py*``` returns the following:

    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py        
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.pyo
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.pyc

I appreciate your looking into this, thank you.

**Comment by ryanss** [comment]
I'm also running MacVim (but downloaded from the website instead of compiled with homebrew) and I have pretty much identical output to you when running the `:version` and `:python sys.version` commands, however I have a lot more directories in my `sys.path` including `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7` where the HTMLParser library (and all the modules that are part of the python standard library) is located.

If you run the vim command `:python import sys; print sys.path` from your terminal vim (not MacVim or mvim) you may see all the correct paths and vim-hackernews will not fail importing HTMLParser. This seems to be an issue with the homebrew MacVim not including all the python paths that it should. You could try downloading a copy of MacVim from the [website](https://code.google.com/p/macvim/) and see if that fixes it.
