### ISSUE TITLE
ImportError: cannot import name recall_pos

### ISSUE THREAD

**Issue by sagarjauhari** [ryanss/vim-hackernews#22]
When updating plugin via Vundle
<pre>
Done! Plugins updated; press u to view changelog
Error detected while processing /Users/sagar/.vim/bundle/vim-hackernews/plugin/hackernews.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name recall_pos
Press ENTER or type command to continue
</pre>

**Comment by barwinco** [comment]
same with vim-plug plug-in manager.

**Comment by sagarjauhari** [comment]
Its strange, I uninstalled the plugin, cleared the Vundle cache and resinstalled. The problem doesn't seem to be there any more. And `:python recall_pos()` seems to be working fine.

**Comment by barwinco** [comment]
same for me :) very strange.

**Comment by ryanss** [comment]
It looks like once you import a python module into an instance of vim it does not get reloaded when a plugin manager updates the plugin. To fix this I will have the plugin reload the `hackernews.py` python module each time the `:HackerNews` command is issued.
