### ISSUE TITLE
Add tests and travis integration

### ISSUE THREAD

**Issue by sagarjauhari** [ryanss/vim-hackernews#23]
The intermittent 'recall_pos()' issue got me thinking that there should be unit tests to prevent breaking the plugin.

**Comment by sagarjauhari** [comment]
Also, add travis badge once #24 has merged.

**Comment by ryanss** [comment]
Added in commits 631a979480b24f03f5b7cfab49353da1cb2f4cb7 and 65a20329dc6be08ce48dbbd51b176df0587efca5.
