### ISSUE TITLE
Support Vim compiled with python3

### ISSUE THREAD

**Issue by mvasilkov** [ryanss/vim-hackernews#28]
My Vim is built --with-python3 --without-python, and e.g. klen/python-mode works great, but this plugin doesn't run.

Sadly, I don't know VimL at all, so no patch here.

**Comment by ryanss** [comment]
I'm just going to leave myself a note here about how I compiled Vim with +python3 on Ubuntu:

```bash
$ sudo apt-get remove vim-common vim-runtime
$ sudo apt-get build-dep vim
$ sudo apt-get install mercurial
$ hg clone https://vim.googlecode.com/hg/ vim
$ cd vim
$ ./configure --enable-python3interp
$ make
$ sudo make install
$ sudo cp /usr/local/bin/vim /usr/bin/vim
```
