### ISSUE TITLE
Make buffer read only and non-modifiable

### ISSUE THREAD

**Issue by jez** [ryanss/vim-hackernews#6]
At least the way I see it, it doesn't make much sense to be able to edit the buffer. To fix this you could add options that make the buffer non-modifiable and read-only.

**Comment by kballenegger** [comment]
```vim
set nomodifiable
```

**Comment by ryanss** [comment]
Right now the plugin opens a single `.hackernews` buffer (with `buftype=nofile`) and does actually modify it to write the front page stories, open articles and comments, etc. I could wrap the `bwrite` helper function with commands to make the buffer `modifiable` to write new content then set it back to `nomodifiable` when it's done, but that breaks using `u` and `Ctrl+r` for going backward and forward. I could overwrite the undo and redo functionality in vim for `filetype=hackernews` but I want to make as few changes to the defaults as possible.

In the future if the plugin changes to opening links into separate buffers I could definitely set `nomodifiable` on them. It's something I will keep in mind.

**Comment by kballenegger** [comment]
Didn't realize it all used the same buffer. Switching between buffers and re-mapping `u`/`ctrl-r` makes sense to me. It'll also make for a more pleasant experience, since it'd now be easy to simply use the full power of Vim's buffer navigation.
