### ISSUE TITLE
Friendlier mapping

### ISSUE THREAD

**Issue by kballenegger** [ryanss/vim-hackernews#7]
A cleaner interface would make it nicer to use and remove a wide variety of custom mappings & settings people use for text editing. Some suggestions for the HN buffer:

```vim
set nomodifiable
set colorcolumn=0
set nocursorline
set noshowmode
set noshowcmd
set noruler
set laststatus=0
set noswapfile
hi! link FoldColumn Normal
set foldcolumn=10
set nonumber
set norelativenumber
set hidden
set textwidth=0

" ignore the value of these mappings, the point is
" that they remap conceptual next/previous to
" stories/comments and not lines
nunmap n
nunmap N
noremap n 7jnz<CR>
noremap N Nz<CR>
map <PageUp> N
map <Left> N
map p N
map <PageDown> n
map <Right> n
map Q :q!<CR>
map gg ggn
map G GN
```

Plus, it'd be nice to be able to hook in custom vimscript for the HN buffers. There's some extra non-common stuff I'd like to disable in HN mode, e.g.:

```
highlight clear OverLength
highlight clear ExtraWhitespace
```

(I took most of this configuration from a custom vim script I made in order to give a talk with "slides" which were just sections in a markdown file in a vim buffer.)

**Comment by ryanss** [comment]
I like the idea of the `.hackernews` buffer keeping all the settings a user has specified. Off the top of my head I can't think of any settings that should absolutely have a specific value to improve the experience of using the plugin.
